apiVersion: v1
kind: ConfigMap
metadata:
  name: vanus-stat
  namespace: vanus
data:
  server.yaml: |-
    port: 8088
    mongodb:
      address: "cluster1.odfrc.mongodb.net"
      database: "vanus-cloud-prod"
      username: "vanus-cloud-prod-rw"
      password: ""
---
apiVersion: v1
kind: Service
metadata:
  name: vanus-stat
  namespace: vanus
spec:
  ports:
  - name: apiserver
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: vanus-stat
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vanus-stat
  name: vanus-stat
  namespace: vanus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vanus-stat
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vanus-stat
    spec:
      containers:
      - image: public.ecr.aws/vanus/stat:jiangkai
        imagePullPolicy: Always
        name: apiserver
        ports:
        - containerPort: 8088
          name: apiserver
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2000Mi
          requests:
            cpu: "2"
            memory: 2000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /vanus-cloud/config
          name: vanus-stat
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: vanus-stat
        name: vanus-stat
