version: '3'
services:
  stat:
    container_name: stat
    image: public.ecr.aws/vanus/stat:jiangkai
    expose:
      - 8088
    ports:
      - "8088:8088"
    volumes:
      - ./config/server.yaml:/vanus-cloud/config/server.yaml
    networks:
      - vanus
networks:
  vanus:
    driver: bridge
